// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver

import (
	"context"
	"net/http"
)



// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface { 
	GetAccount(http.ResponseWriter, *http.Request)
	GetBalanceForAccount(http.ResponseWriter, *http.Request)
	GetBillingForAccount(http.ResponseWriter, *http.Request)
	GetConcessions(http.ResponseWriter, *http.Request)
	GetDERForServicePoint(http.ResponseWriter, *http.Request)
	GetInvoicesForAccount(http.ResponseWriter, *http.Request)
	GetPaymentSchedule(http.ResponseWriter, *http.Request)
	GetPlan(http.ResponseWriter, *http.Request)
	GetServicePoint(http.ResponseWriter, *http.Request)
	GetUsageForServicePoint(http.ResponseWriter, *http.Request)
	ListAccounts(http.ResponseWriter, *http.Request)
	ListBalancesBulk(http.ResponseWriter, *http.Request)
	ListBalancesForAccounts(http.ResponseWriter, *http.Request)
	ListBillingBulk(http.ResponseWriter, *http.Request)
	ListBillingForAccounts(http.ResponseWriter, *http.Request)
	ListDERBulk(http.ResponseWriter, *http.Request)
	ListDERForServicePoints(http.ResponseWriter, *http.Request)
	ListInvoicesBulk(http.ResponseWriter, *http.Request)
	ListInvoicesForAccounts(http.ResponseWriter, *http.Request)
	ListPlans(http.ResponseWriter, *http.Request)
	ListServicePoints(http.ResponseWriter, *http.Request)
	ListUsageBulk(http.ResponseWriter, *http.Request)
	ListUsageForServicePoints(http.ResponseWriter, *http.Request)
}


// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface { 
	GetAccount(context.Context, string, string, string, string, string, string, string) (ImplResponse, error)
	GetBalanceForAccount(context.Context, string, string, string, string, string, string, string) (ImplResponse, error)
	GetBillingForAccount(context.Context, string, string, string, string, int32, int32, string, string, string, string, string) (ImplResponse, error)
	GetConcessions(context.Context, string, string, string, string, string, string, string) (ImplResponse, error)
	GetDERForServicePoint(context.Context, string, string, string, string, string, string, string) (ImplResponse, error)
	GetInvoicesForAccount(context.Context, string, string, string, string, int32, int32, string, string, string, string, string) (ImplResponse, error)
	GetPaymentSchedule(context.Context, string, string, string, string, string, string, string) (ImplResponse, error)
	GetPlan(context.Context, string, string, string) (ImplResponse, error)
	GetServicePoint(context.Context, string, string, string, string, string, string, string) (ImplResponse, error)
	GetUsageForServicePoint(context.Context, string, string, string, string, IntervalRead, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListAccounts(context.Context, string, State, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListBalancesBulk(context.Context, string, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListBalancesForAccounts(context.Context, string, RequestAccountIdList, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListBillingBulk(context.Context, string, string, string, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListBillingForAccounts(context.Context, string, RequestAccountIdList, string, string, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListDERBulk(context.Context, string, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListDERForServicePoints(context.Context, string, RequestServicePointIdList, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListInvoicesBulk(context.Context, string, string, string, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListInvoicesForAccounts(context.Context, string, RequestAccountIdList, string, string, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListPlans(context.Context, string, ListPlanType, FuelType, Effective, string, string, int32, int32, string) (ImplResponse, error)
	ListServicePoints(context.Context, string, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListUsageBulk(context.Context, string, IntervalRead, string, string, int32, int32, string, string, string, string, string) (ImplResponse, error)
	ListUsageForServicePoints(context.Context, string, RequestServicePointIdList, string, string, IntervalRead, int32, int32, string, string, string, string, string) (ImplResponse, error)
}
