// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver

import (
	"context"
	"net/http"
	"errors"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() DefaultAPIServicer {
	return &DefaultAPIService{}
}

// GetAccount - Get Energy Account Detail
func (s *DefaultAPIService) GetAccount(ctx context.Context, accountId string, xV string, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update GetAccount with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyAccountDetailResponseV4{}) or use other options such as http.Ok ...
	// return Response(200, EnergyAccountDetailResponseV4{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(404, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAccount method not implemented")
}

// GetBalanceForAccount - Get Balance For Energy Account
func (s *DefaultAPIService) GetBalanceForAccount(ctx context.Context, accountId string, xV string, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update GetBalanceForAccount with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyBalanceResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyBalanceResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(404, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetBalanceForAccount method not implemented")
}

// GetBillingForAccount - Get Billing For Account
func (s *DefaultAPIService) GetBillingForAccount(ctx context.Context, accountId string, xV string, newestTime string, oldestTime string, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update GetBillingForAccount with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyBillingListResponseV3{}) or use other options such as http.Ok ...
	// return Response(200, EnergyBillingListResponseV3{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(404, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetBillingForAccount method not implemented")
}

// GetConcessions - Get Concessions
func (s *DefaultAPIService) GetConcessions(ctx context.Context, accountId string, xV string, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update GetConcessions with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyConcessionsResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyConcessionsResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(404, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetConcessions method not implemented")
}

// GetDERForServicePoint - Get DER For Service Point
func (s *DefaultAPIService) GetDERForServicePoint(ctx context.Context, servicePointId string, xV string, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update GetDERForServicePoint with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyDerDetailResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyDerDetailResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(404, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDERForServicePoint method not implemented")
}

// GetInvoicesForAccount - Get Invoices For Account
func (s *DefaultAPIService) GetInvoicesForAccount(ctx context.Context, accountId string, xV string, newestDate string, oldestDate string, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update GetInvoicesForAccount with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyInvoiceListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyInvoiceListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(404, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetInvoicesForAccount method not implemented")
}

// GetPaymentSchedule - Get Agreed Payment Schedule
func (s *DefaultAPIService) GetPaymentSchedule(ctx context.Context, accountId string, xV string, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update GetPaymentSchedule with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyPaymentScheduleResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyPaymentScheduleResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(404, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetPaymentSchedule method not implemented")
}

// GetPlan - Get Generic Plan Detail
func (s *DefaultAPIService) GetPlan(ctx context.Context, planId string, xV string, xMinV string) (ImplResponse, error) {
	// TODO - update GetPlan with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyPlanResponseV3{}) or use other options such as http.Ok ...
	// return Response(200, EnergyPlanResponseV3{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(404, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetPlan method not implemented")
}

// GetServicePoint - Get Service Point Detail
func (s *DefaultAPIService) GetServicePoint(ctx context.Context, servicePointId string, xV string, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update GetServicePoint with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyServicePointDetailResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyServicePointDetailResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(404, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetServicePoint method not implemented")
}

// GetUsageForServicePoint - Get Usage For Service Point
func (s *DefaultAPIService) GetUsageForServicePoint(ctx context.Context, servicePointId string, xV string, oldestDate string, newestDate string, intervalReads IntervalRead, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update GetUsageForServicePoint with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyUsageListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyUsageListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(404, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(404, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetUsageForServicePoint method not implemented")
}

// ListAccounts - Get Energy Accounts
func (s *DefaultAPIService) ListAccounts(ctx context.Context, xV string, openStatus State, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListAccounts with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyAccountListResponseV2{}) or use other options such as http.Ok ...
	// return Response(200, EnergyAccountListResponseV2{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListAccounts method not implemented")
}

// ListBalancesBulk - Get Bulk Balances for Energy
func (s *DefaultAPIService) ListBalancesBulk(ctx context.Context, xV string, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListBalancesBulk with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyBalanceListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyBalanceListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListBalancesBulk method not implemented")
}

// ListBalancesForAccounts - Get Balances For Specific Energy Accounts
func (s *DefaultAPIService) ListBalancesForAccounts(ctx context.Context, xV string, requestAccountIdList RequestAccountIdList, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListBalancesForAccounts with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyBalanceListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyBalanceListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListBalancesForAccounts method not implemented")
}

// ListBillingBulk - Get Bulk Billing
func (s *DefaultAPIService) ListBillingBulk(ctx context.Context, xV string, newestTime string, oldestTime string, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListBillingBulk with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyBillingListResponseV3{}) or use other options such as http.Ok ...
	// return Response(200, EnergyBillingListResponseV3{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListBillingBulk method not implemented")
}

// ListBillingForAccounts - Get Billing For Specific Accounts
func (s *DefaultAPIService) ListBillingForAccounts(ctx context.Context, xV string, requestAccountIdList RequestAccountIdList, newestTime string, oldestTime string, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListBillingForAccounts with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyBillingListResponseV3{}) or use other options such as http.Ok ...
	// return Response(200, EnergyBillingListResponseV3{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListBillingForAccounts method not implemented")
}

// ListDERBulk - Get Bulk DER
func (s *DefaultAPIService) ListDERBulk(ctx context.Context, xV string, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListDERBulk with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyDerListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyDerListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListDERBulk method not implemented")
}

// ListDERForServicePoints - Get DER For Specific Service Points
func (s *DefaultAPIService) ListDERForServicePoints(ctx context.Context, xV string, requestServicePointIdList RequestServicePointIdList, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListDERForServicePoints with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyDerListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyDerListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListDERForServicePoints method not implemented")
}

// ListInvoicesBulk - Get Bulk Invoices
func (s *DefaultAPIService) ListInvoicesBulk(ctx context.Context, xV string, newestDate string, oldestDate string, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListInvoicesBulk with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyInvoiceListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyInvoiceListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListInvoicesBulk method not implemented")
}

// ListInvoicesForAccounts - Get Invoices For Specific Accounts
func (s *DefaultAPIService) ListInvoicesForAccounts(ctx context.Context, xV string, requestAccountIdList RequestAccountIdList, newestDate string, oldestDate string, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListInvoicesForAccounts with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyInvoiceListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyInvoiceListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListInvoicesForAccounts method not implemented")
}

// ListPlans - Get Generic Plans
func (s *DefaultAPIService) ListPlans(ctx context.Context, xV string, type_ ListPlanType, fuelType FuelType, effective Effective, updatedSince string, brand string, page int32, pageSize int32, xMinV string) (ImplResponse, error) {
	// TODO - update ListPlans with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyPlanListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyPlanListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListPlans method not implemented")
}

// ListServicePoints - Get Service Points
func (s *DefaultAPIService) ListServicePoints(ctx context.Context, xV string, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListServicePoints with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyServicePointListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyServicePointListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListServicePoints method not implemented")
}

// ListUsageBulk - Get Bulk Usage
func (s *DefaultAPIService) ListUsageBulk(ctx context.Context, xV string, intervalReads IntervalRead, oldestDate string, newestDate string, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListUsageBulk with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyUsageListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyUsageListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListUsageBulk method not implemented")
}

// ListUsageForServicePoints - Get Usage For Specific Service Points
func (s *DefaultAPIService) ListUsageForServicePoints(ctx context.Context, xV string, requestServicePointIdList RequestServicePointIdList, oldestDate string, newestDate string, intervalReads IntervalRead, page int32, pageSize int32, xMinV string, xFapiInteractionId string, xFapiAuthDate string, xFapiCustomerIpAddress string, xCdsClientHeaders string) (ImplResponse, error) {
	// TODO - update ListUsageForServicePoints with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EnergyUsageListResponse{}) or use other options such as http.Ok ...
	// return Response(200, EnergyUsageListResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(400, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(406, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(406, ResponseErrorListV2{}), nil

	// TODO: Uncomment the next line to return response Response(422, ResponseErrorListV2{}) or use other options such as http.Ok ...
	// return Response(422, ResponseErrorListV2{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListUsageForServicePoints method not implemented")
}
