// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyPlanContractV3IntrinsicGreenPower - Describes intrinsic green power for the plan.  If present then the plan includes a percentage of green power in the base plan. Should not be present for gas contracts
type EnergyPlanContractV3IntrinsicGreenPower struct {

	// Percentage of green power intrinsically included in the plan
	GreenPercentage string `json:"greenPercentage"`
}

// AssertEnergyPlanContractV3IntrinsicGreenPowerRequired checks if the required fields are not zero-ed
func AssertEnergyPlanContractV3IntrinsicGreenPowerRequired(obj EnergyPlanContractV3IntrinsicGreenPower) error {
	elements := map[string]interface{}{
		"greenPercentage": obj.GreenPercentage,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyPlanContractV3IntrinsicGreenPowerConstraints checks if the values respects the defined constraints
func AssertEnergyPlanContractV3IntrinsicGreenPowerConstraints(obj EnergyPlanContractV3IntrinsicGreenPower) error {
	return nil
}
