// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyPlanDiscountsInnerFixedAmount - Required if methodUType is fixedAmount
type EnergyPlanDiscountsInnerFixedAmount struct {

	// The amount of the discount
	Amount string `json:"amount"`
}

// AssertEnergyPlanDiscountsInnerFixedAmountRequired checks if the required fields are not zero-ed
func AssertEnergyPlanDiscountsInnerFixedAmountRequired(obj EnergyPlanDiscountsInnerFixedAmount) error {
	elements := map[string]interface{}{
		"amount": obj.Amount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyPlanDiscountsInnerFixedAmountConstraints checks if the values respects the defined constraints
func AssertEnergyPlanDiscountsInnerFixedAmountConstraints(obj EnergyPlanDiscountsInnerFixedAmount) error {
	return nil
}
