// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyInvoiceAccountCharges - Object contains account level charges and credits related to electricity usage
type EnergyInvoiceAccountCharges struct {

	// The aggregate total of account level charges for the period covered by the invoice
	TotalCharges string `json:"totalCharges"`

	// The aggregate total of account level discounts or credits for the period covered by the invoice
	TotalDiscounts string `json:"totalDiscounts"`

	// The total GST for all account level charges.  If absent then zero is assumed
	TotalGst string `json:"totalGst,omitempty"`
}

// AssertEnergyInvoiceAccountChargesRequired checks if the required fields are not zero-ed
func AssertEnergyInvoiceAccountChargesRequired(obj EnergyInvoiceAccountCharges) error {
	elements := map[string]interface{}{
		"totalCharges": obj.TotalCharges,
		"totalDiscounts": obj.TotalDiscounts,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyInvoiceAccountChargesConstraints checks if the values respects the defined constraints
func AssertEnergyInvoiceAccountChargesConstraints(obj EnergyInvoiceAccountCharges) error {
	return nil
}
