// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyUsageReadIntervalReadReadQualities struct {

	// Start interval for read quality flag. First read begins at 1
	StartInterval int32 `json:"startInterval"`

	// End interval for read quality flag
	EndInterval int32 `json:"endInterval"`

	// The quality of the read taken
	Quality string `json:"quality"`
}

// AssertEnergyUsageReadIntervalReadReadQualitiesRequired checks if the required fields are not zero-ed
func AssertEnergyUsageReadIntervalReadReadQualitiesRequired(obj EnergyUsageReadIntervalReadReadQualities) error {
	elements := map[string]interface{}{
		"startInterval": obj.StartInterval,
		"endInterval": obj.EndInterval,
		"quality": obj.Quality,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyUsageReadIntervalReadReadQualitiesConstraints checks if the values respects the defined constraints
func AssertEnergyUsageReadIntervalReadReadQualitiesConstraints(obj EnergyUsageReadIntervalReadReadQualities) error {
	return nil
}
