// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyBillingUsageTransactionV2Adjustments struct {

	// The amount of the adjustment
	Amount string `json:"amount"`

	// A free text description of the adjustment
	Description string `json:"description"`
}

// AssertEnergyBillingUsageTransactionV2AdjustmentsRequired checks if the required fields are not zero-ed
func AssertEnergyBillingUsageTransactionV2AdjustmentsRequired(obj EnergyBillingUsageTransactionV2Adjustments) error {
	elements := map[string]interface{}{
		"amount": obj.Amount,
		"description": obj.Description,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyBillingUsageTransactionV2AdjustmentsConstraints checks if the values respects the defined constraints
func AssertEnergyBillingUsageTransactionV2AdjustmentsConstraints(obj EnergyBillingUsageTransactionV2Adjustments) error {
	return nil
}
