// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyBillingOnceOffTransaction struct {

	// The ID of the service point to which this transaction applies if any
	ServicePointId string `json:"servicePointId,omitempty"`

	// The number of the invoice in which this transaction is included if it has been issued
	InvoiceNumber string `json:"invoiceNumber,omitempty"`

	// The amount of the charge or credit.  A positive value indicates a charge and a negative value indicates a credit
	Amount string `json:"amount"`

	// A free text description of the item
	Description string `json:"description"`
}

// AssertEnergyBillingOnceOffTransactionRequired checks if the required fields are not zero-ed
func AssertEnergyBillingOnceOffTransactionRequired(obj EnergyBillingOnceOffTransaction) error {
	elements := map[string]interface{}{
		"amount": obj.Amount,
		"description": obj.Description,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyBillingOnceOffTransactionConstraints checks if the values respects the defined constraints
func AssertEnergyBillingOnceOffTransactionConstraints(obj EnergyBillingOnceOffTransaction) error {
	return nil
}
