// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyPaymentScheduleManualPayment - Represents a manual payment schedule where the customer pays in response to a delivered statement. Mandatory if paymentScheduleUType is set to manualPayment
type EnergyPaymentScheduleManualPayment struct {

	// The frequency with which a bill will be issued.  Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)
	BillFrequency string `json:"billFrequency"`
}

// AssertEnergyPaymentScheduleManualPaymentRequired checks if the required fields are not zero-ed
func AssertEnergyPaymentScheduleManualPaymentRequired(obj EnergyPaymentScheduleManualPayment) error {
	elements := map[string]interface{}{
		"billFrequency": obj.BillFrequency,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyPaymentScheduleManualPaymentConstraints checks if the values respects the defined constraints
func AssertEnergyPaymentScheduleManualPaymentConstraints(obj EnergyPaymentScheduleManualPayment) error {
	return nil
}
