// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyInvoiceListResponseData struct {

	// Array of invoices sorted by issue date in descending order
	Invoices []EnergyInvoice `json:"invoices"`
}

// AssertEnergyInvoiceListResponseDataRequired checks if the required fields are not zero-ed
func AssertEnergyInvoiceListResponseDataRequired(obj EnergyInvoiceListResponseData) error {
	elements := map[string]interface{}{
		"invoices": obj.Invoices,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Invoices {
		if err := AssertEnergyInvoiceRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyInvoiceListResponseDataConstraints checks if the values respects the defined constraints
func AssertEnergyInvoiceListResponseDataConstraints(obj EnergyInvoiceListResponseData) error {
	return nil
}
