// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyPlanGreenPowerChargesInnerTiersInner struct {

	// The upper percentage of green power used applicable for this tier
	PercentGreen string `json:"percentGreen"`

	// The rate of the charge if the type implies the application of a rate
	Rate string `json:"rate,omitempty"`

	// The amount of the charge if the type implies the application of a fixed amount
	Amount string `json:"amount,omitempty"`
}

// AssertEnergyPlanGreenPowerChargesInnerTiersInnerRequired checks if the required fields are not zero-ed
func AssertEnergyPlanGreenPowerChargesInnerTiersInnerRequired(obj EnergyPlanGreenPowerChargesInnerTiersInner) error {
	elements := map[string]interface{}{
		"percentGreen": obj.PercentGreen,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyPlanGreenPowerChargesInnerTiersInnerConstraints checks if the values respects the defined constraints
func AssertEnergyPlanGreenPowerChargesInnerTiersInnerConstraints(obj EnergyPlanGreenPowerChargesInnerTiersInner) error {
	return nil
}
