// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyPlanTariffPeriodV2InnerSingleRate - Object representing a single rate.  Required if rateBlockUType is singleRate
type EnergyPlanTariffPeriodV2InnerSingleRate struct {

	// Display name of the rate
	DisplayName string `json:"displayName"`

	// Description of the rate
	Description string `json:"description,omitempty"`

	// The block rate (unit price) for any usage above the included fixed usage, in dollars per kWh inclusive of GST.  Only required if pricingModel field is ‘QUOTA’
	GeneralUnitPrice string `json:"generalUnitPrice,omitempty"`

	// Array of controlled load rates in order of usage volume
	Rates []EnergyPlanTariffPeriodV2InnerSingleRateRatesInner `json:"rates"`

	// Usage period for which the block rate applies. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)
	Period string `json:"period,omitempty"`
}

// AssertEnergyPlanTariffPeriodV2InnerSingleRateRequired checks if the required fields are not zero-ed
func AssertEnergyPlanTariffPeriodV2InnerSingleRateRequired(obj EnergyPlanTariffPeriodV2InnerSingleRate) error {
	elements := map[string]interface{}{
		"displayName": obj.DisplayName,
		"rates": obj.Rates,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Rates {
		if err := AssertEnergyPlanTariffPeriodV2InnerSingleRateRatesInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyPlanTariffPeriodV2InnerSingleRateConstraints checks if the values respects the defined constraints
func AssertEnergyPlanTariffPeriodV2InnerSingleRateConstraints(obj EnergyPlanTariffPeriodV2InnerSingleRate) error {
	return nil
}
