// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyPlanFeesInner struct {

	// The type of the fee
	Type string `json:"type"`

	// The term of the fee
	Term string `json:"term"`

	// The fee amount. Required if term is not PERCENT_OF_BILL
	Amount string `json:"amount,omitempty"`

	// The fee rate. Required if term is PERCENT_OF_BILL
	Rate string `json:"rate,omitempty"`

	// A description of the fee
	Description string `json:"description,omitempty"`
}

// AssertEnergyPlanFeesInnerRequired checks if the required fields are not zero-ed
func AssertEnergyPlanFeesInnerRequired(obj EnergyPlanFeesInner) error {
	elements := map[string]interface{}{
		"type": obj.Type,
		"term": obj.Term,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyPlanFeesInnerConstraints checks if the values respects the defined constraints
func AssertEnergyPlanFeesInnerConstraints(obj EnergyPlanFeesInner) error {
	return nil
}
