// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyAccountDetailV4AllOf - The array of plans containing service points and associated plan details
type EnergyAccountDetailV4AllOf struct {

	// The array of plans containing service points and associated plan details
	Plans []EnergyAccountDetailV4AllOfPlans `json:"plans"`
}

// AssertEnergyAccountDetailV4AllOfRequired checks if the required fields are not zero-ed
func AssertEnergyAccountDetailV4AllOfRequired(obj EnergyAccountDetailV4AllOf) error {
	elements := map[string]interface{}{
		"plans": obj.Plans,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Plans {
		if err := AssertEnergyAccountDetailV4AllOfPlansRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyAccountDetailV4AllOfConstraints checks if the values respects the defined constraints
func AssertEnergyAccountDetailV4AllOfConstraints(obj EnergyAccountDetailV4AllOf) error {
	return nil
}
