// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type RequestAccountIdListData struct {

	// Array of specific accountIds to obtain data for
	AccountIds []string `json:"accountIds"`
}

// AssertRequestAccountIdListDataRequired checks if the required fields are not zero-ed
func AssertRequestAccountIdListDataRequired(obj RequestAccountIdListData) error {
	elements := map[string]interface{}{
		"accountIds": obj.AccountIds,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRequestAccountIdListDataConstraints checks if the values respects the defined constraints
func AssertRequestAccountIdListDataConstraints(obj RequestAccountIdListData) error {
	return nil
}
