// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyBillingListResponseV3Data struct {

	// Array of transactions sorted by date and time in descending order
	Transactions []EnergyBillingTransactionV3 `json:"transactions"`
}

// AssertEnergyBillingListResponseV3DataRequired checks if the required fields are not zero-ed
func AssertEnergyBillingListResponseV3DataRequired(obj EnergyBillingListResponseV3Data) error {
	elements := map[string]interface{}{
		"transactions": obj.Transactions,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Transactions {
		if err := AssertEnergyBillingTransactionV3Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyBillingListResponseV3DataConstraints checks if the values respects the defined constraints
func AssertEnergyBillingListResponseV3DataConstraints(obj EnergyBillingListResponseV3Data) error {
	return nil
}
