// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyBillingListResponseV3 struct {

	Data EnergyBillingListResponseV3Data `json:"data"`

	Links LinksPaginated `json:"links"`

	Meta MetaPaginated `json:"meta"`
}

// AssertEnergyBillingListResponseV3Required checks if the required fields are not zero-ed
func AssertEnergyBillingListResponseV3Required(obj EnergyBillingListResponseV3) error {
	elements := map[string]interface{}{
		"data": obj.Data,
		"links": obj.Links,
		"meta": obj.Meta,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertEnergyBillingListResponseV3DataRequired(obj.Data); err != nil {
		return err
	}
	if err := AssertLinksPaginatedRequired(obj.Links); err != nil {
		return err
	}
	if err := AssertMetaPaginatedRequired(obj.Meta); err != nil {
		return err
	}
	return nil
}

// AssertEnergyBillingListResponseV3Constraints checks if the values respects the defined constraints
func AssertEnergyBillingListResponseV3Constraints(obj EnergyBillingListResponseV3) error {
	return nil
}
