// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyPlanTariffPeriodV2InnerBandedDailySupplyChargesInner struct {

	// The amount of daily supply charge for the band, in dollars per day exclusive of GST
	UnitPrice string `json:"unitPrice"`

	// The measurement unit of rate. Assumed to be DAYS if absent
	MeasureUnit string `json:"measureUnit,omitempty"`

	// Volume the charge applies to
	Volume float32 `json:"volume,omitempty"`
}

// AssertEnergyPlanTariffPeriodV2InnerBandedDailySupplyChargesInnerRequired checks if the required fields are not zero-ed
func AssertEnergyPlanTariffPeriodV2InnerBandedDailySupplyChargesInnerRequired(obj EnergyPlanTariffPeriodV2InnerBandedDailySupplyChargesInner) error {
	elements := map[string]interface{}{
		"unitPrice": obj.UnitPrice,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyPlanTariffPeriodV2InnerBandedDailySupplyChargesInnerConstraints checks if the values respects the defined constraints
func AssertEnergyPlanTariffPeriodV2InnerBandedDailySupplyChargesInnerConstraints(obj EnergyPlanTariffPeriodV2InnerBandedDailySupplyChargesInner) error {
	return nil
}
