// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyPlanListResponseData struct {

	// Array of plans
	Plans []EnergyPlan `json:"plans"`
}

// AssertEnergyPlanListResponseDataRequired checks if the required fields are not zero-ed
func AssertEnergyPlanListResponseDataRequired(obj EnergyPlanListResponseData) error {
	elements := map[string]interface{}{
		"plans": obj.Plans,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Plans {
		if err := AssertEnergyPlanRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyPlanListResponseDataConstraints checks if the values respects the defined constraints
func AssertEnergyPlanListResponseDataConstraints(obj EnergyPlanListResponseData) error {
	return nil
}
