// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyPlanIncentivesInner struct {

	// The display name of the incentive
	DisplayName string `json:"displayName"`

	// The description of the incentive
	Description string `json:"description"`

	// The type of the incentive
	Category string `json:"category"`

	// A display message outlining an eligibility criteria that may apply
	Eligibility string `json:"eligibility,omitempty"`
}

// AssertEnergyPlanIncentivesInnerRequired checks if the required fields are not zero-ed
func AssertEnergyPlanIncentivesInnerRequired(obj EnergyPlanIncentivesInner) error {
	elements := map[string]interface{}{
		"displayName": obj.DisplayName,
		"description": obj.Description,
		"category": obj.Category,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyPlanIncentivesInnerConstraints checks if the values respects the defined constraints
func AssertEnergyPlanIncentivesInnerConstraints(obj EnergyPlanIncentivesInner) error {
	return nil
}
