// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyServicePointListResponse struct {

	Data EnergyServicePointListResponseData `json:"data"`

	Links LinksPaginated `json:"links"`

	Meta MetaPaginated `json:"meta"`
}

// AssertEnergyServicePointListResponseRequired checks if the required fields are not zero-ed
func AssertEnergyServicePointListResponseRequired(obj EnergyServicePointListResponse) error {
	elements := map[string]interface{}{
		"data": obj.Data,
		"links": obj.Links,
		"meta": obj.Meta,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertEnergyServicePointListResponseDataRequired(obj.Data); err != nil {
		return err
	}
	if err := AssertLinksPaginatedRequired(obj.Links); err != nil {
		return err
	}
	if err := AssertMetaPaginatedRequired(obj.Meta); err != nil {
		return err
	}
	return nil
}

// AssertEnergyServicePointListResponseConstraints checks if the values respects the defined constraints
func AssertEnergyServicePointListResponseConstraints(obj EnergyServicePointListResponse) error {
	return nil
}
