// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// ResponseErrorListV2Meta - Additional data for customised error codes
type ResponseErrorListV2Meta struct {

	// The CDR error code URN which the application-specific error code extends. Mandatory if the error `code` is an application-specific error rather than a standardised error code.
	Urn string `json:"urn,omitempty"`
}

// AssertResponseErrorListV2MetaRequired checks if the required fields are not zero-ed
func AssertResponseErrorListV2MetaRequired(obj ResponseErrorListV2Meta) error {
	return nil
}

// AssertResponseErrorListV2MetaConstraints checks if the values respects the defined constraints
func AssertResponseErrorListV2MetaConstraints(obj ResponseErrorListV2Meta) error {
	return nil
}
