// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type Links struct {

	// Fully qualified link that generated the current response document
	Self string `json:"self"`
}

// AssertLinksRequired checks if the required fields are not zero-ed
func AssertLinksRequired(obj Links) error {
	elements := map[string]interface{}{
		"self": obj.Self,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertLinksConstraints checks if the values respects the defined constraints
func AssertLinksConstraints(obj Links) error {
	return nil
}
