// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyServicePointConsumerProfile struct {

	// A code that defines the consumer class as defined in the National Energy Retail Regulations, or in overriding Jurisdictional instruments
	Classification string `json:"classification,omitempty"`

	// A code that defines the consumption threshold as defined in the National Energy Retail Regulations, or in overriding Jurisdictional instruments. Note the details of enumeration values below: <ul><li>**LOW** - Consumption is less than the ‘lower consumption threshold’ as defined in the National Energy Retail Regulations</li><li>**MEDIUM** - Consumption is equal to or greater than the ‘lower consumption threshold’, but less than the ‘upper consumption threshold’, as defined in the National Energy Retail Regulations</li><li>**HIGH** - Consumption is equal to or greater than the ‘upper consumption threshold’ as defined in the National Energy Retail Regulations</li></ul>
	Threshold string `json:"threshold,omitempty"`
}

// AssertEnergyServicePointConsumerProfileRequired checks if the required fields are not zero-ed
func AssertEnergyServicePointConsumerProfileRequired(obj EnergyServicePointConsumerProfile) error {
	return nil
}

// AssertEnergyServicePointConsumerProfileConstraints checks if the values respects the defined constraints
func AssertEnergyServicePointConsumerProfileConstraints(obj EnergyServicePointConsumerProfile) error {
	return nil
}
