// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyAccountListResponseV2Data struct {

	// Array of accounts
	Accounts []EnergyAccountV2 `json:"accounts"`
}

// AssertEnergyAccountListResponseV2DataRequired checks if the required fields are not zero-ed
func AssertEnergyAccountListResponseV2DataRequired(obj EnergyAccountListResponseV2Data) error {
	elements := map[string]interface{}{
		"accounts": obj.Accounts,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Accounts {
		if err := AssertEnergyAccountV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyAccountListResponseV2DataConstraints checks if the values respects the defined constraints
func AssertEnergyAccountListResponseV2DataConstraints(obj EnergyAccountListResponseV2Data) error {
	return nil
}
