// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type CommonPhysicalAddress struct {

	// The type of address object present
	AddressUType string `json:"addressUType"`

	Simple CommonSimpleAddress `json:"simple,omitempty"`

	Paf CommonPafAddress `json:"paf,omitempty"`
}

// AssertCommonPhysicalAddressRequired checks if the required fields are not zero-ed
func AssertCommonPhysicalAddressRequired(obj CommonPhysicalAddress) error {
	elements := map[string]interface{}{
		"addressUType": obj.AddressUType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCommonSimpleAddressRequired(obj.Simple); err != nil {
		return err
	}
	if err := AssertCommonPafAddressRequired(obj.Paf); err != nil {
		return err
	}
	return nil
}

// AssertCommonPhysicalAddressConstraints checks if the values respects the defined constraints
func AssertCommonPhysicalAddressConstraints(obj CommonPhysicalAddress) error {
	return nil
}
