// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyPlanDiscountsInnerPercentOverThreshold - Required if methodUType is percentOverThreshold
type EnergyPlanDiscountsInnerPercentOverThreshold struct {

	// The rate of the discount over the usage amount
	Rate string `json:"rate"`

	// The usage amount threshold above which the discount applies
	UsageAmount string `json:"usageAmount"`
}

// AssertEnergyPlanDiscountsInnerPercentOverThresholdRequired checks if the required fields are not zero-ed
func AssertEnergyPlanDiscountsInnerPercentOverThresholdRequired(obj EnergyPlanDiscountsInnerPercentOverThreshold) error {
	elements := map[string]interface{}{
		"rate": obj.Rate,
		"usageAmount": obj.UsageAmount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyPlanDiscountsInnerPercentOverThresholdConstraints checks if the values respects the defined constraints
func AssertEnergyPlanDiscountsInnerPercentOverThresholdConstraints(obj EnergyPlanDiscountsInnerPercentOverThreshold) error {
	return nil
}
