// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyPlanAdditionalInformation - Object that contains links to additional information on specific topics
type EnergyPlanAdditionalInformation struct {

	// A link to a general overview of the plan
	OverviewUri string `json:"overviewUri,omitempty"`

	// A link to terms and conditions for the plan
	TermsUri string `json:"termsUri,omitempty"`

	// A link to detail on eligibility criteria for the plan
	EligibilityUri string `json:"eligibilityUri,omitempty"`

	// A link to detail on pricing for the plan
	PricingUri string `json:"pricingUri,omitempty"`

	// A link to detail on bundles that this plan can be a part of
	BundleUri string `json:"bundleUri,omitempty"`
}

// AssertEnergyPlanAdditionalInformationRequired checks if the required fields are not zero-ed
func AssertEnergyPlanAdditionalInformationRequired(obj EnergyPlanAdditionalInformation) error {
	return nil
}

// AssertEnergyPlanAdditionalInformationConstraints checks if the values respects the defined constraints
func AssertEnergyPlanAdditionalInformationConstraints(obj EnergyPlanAdditionalInformation) error {
	return nil
}
