// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyInvoicePayOnTimeDiscount - A discount for on time payment
type EnergyInvoicePayOnTimeDiscount struct {

	// The amount that will be discounted if the invoice is paid by the date specified
	DiscountAmount string `json:"discountAmount"`

	// The GST amount that will be discounted if the invoice is paid by the date specified.  If absent then zero is assumed
	GstAmount string `json:"gstAmount,omitempty"`

	// The date by which the invoice must be paid to receive the pay on time discount
	Date string `json:"date"`
}

// AssertEnergyInvoicePayOnTimeDiscountRequired checks if the required fields are not zero-ed
func AssertEnergyInvoicePayOnTimeDiscountRequired(obj EnergyInvoicePayOnTimeDiscount) error {
	elements := map[string]interface{}{
		"discountAmount": obj.DiscountAmount,
		"date": obj.Date,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyInvoicePayOnTimeDiscountConstraints checks if the values respects the defined constraints
func AssertEnergyInvoicePayOnTimeDiscountConstraints(obj EnergyInvoicePayOnTimeDiscount) error {
	return nil
}
