// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyBalanceListResponseData struct {

	// Array of account balances
	Balances []EnergyBalanceListResponseDataBalances `json:"balances"`
}

// AssertEnergyBalanceListResponseDataRequired checks if the required fields are not zero-ed
func AssertEnergyBalanceListResponseDataRequired(obj EnergyBalanceListResponseData) error {
	elements := map[string]interface{}{
		"balances": obj.Balances,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Balances {
		if err := AssertEnergyBalanceListResponseDataBalancesRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyBalanceListResponseDataConstraints checks if the values respects the defined constraints
func AssertEnergyBalanceListResponseDataConstraints(obj EnergyBalanceListResponseData) error {
	return nil
}
