// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyAccountDetailV4AllOfAuthorisedContacts struct {

	// For people with single names this field need not be present. The single name should be in the lastName field
	FirstName string `json:"firstName,omitempty"`

	// For people with single names the single name should be in this field
	LastName string `json:"lastName"`

	// Field is mandatory but array may be empty
	MiddleNames []string `json:"middleNames,omitempty"`

	// Also known as title or salutation. The prefix to the name (e.g. Mr, Mrs, Ms, Miss, Sir, etc)
	Prefix string `json:"prefix,omitempty"`

	// Used for a trailing suffix to the name (e.g. Jr)
	Suffix string `json:"suffix,omitempty"`
}

// AssertEnergyAccountDetailV4AllOfAuthorisedContactsRequired checks if the required fields are not zero-ed
func AssertEnergyAccountDetailV4AllOfAuthorisedContactsRequired(obj EnergyAccountDetailV4AllOfAuthorisedContacts) error {
	elements := map[string]interface{}{
		"lastName": obj.LastName,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyAccountDetailV4AllOfAuthorisedContactsConstraints checks if the values respects the defined constraints
func AssertEnergyAccountDetailV4AllOfAuthorisedContactsConstraints(obj EnergyAccountDetailV4AllOfAuthorisedContacts) error {
	return nil
}
