// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyPaymentScheduleResponseData struct {

	// Array may be empty if no payment schedule exist
	PaymentSchedules []EnergyPaymentSchedule `json:"paymentSchedules"`
}

// AssertEnergyPaymentScheduleResponseDataRequired checks if the required fields are not zero-ed
func AssertEnergyPaymentScheduleResponseDataRequired(obj EnergyPaymentScheduleResponseData) error {
	elements := map[string]interface{}{
		"paymentSchedules": obj.PaymentSchedules,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.PaymentSchedules {
		if err := AssertEnergyPaymentScheduleRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyPaymentScheduleResponseDataConstraints checks if the values respects the defined constraints
func AssertEnergyPaymentScheduleResponseDataConstraints(obj EnergyPaymentScheduleResponseData) error {
	return nil
}
