// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyServicePointDetailDistributionLossFactor struct {

	// A code used to identify data loss factor for the service point values.  Refer to AEMO distribution loss factor documents for each financial year to interpret
	Code string `json:"code"`

	// Description of the data loss factor code and value
	Description string `json:"description"`

	// The value associated with the loss factor code
	LossValue string `json:"lossValue"`
}

// AssertEnergyServicePointDetailDistributionLossFactorRequired checks if the required fields are not zero-ed
func AssertEnergyServicePointDetailDistributionLossFactorRequired(obj EnergyServicePointDetailDistributionLossFactor) error {
	elements := map[string]interface{}{
		"code": obj.Code,
		"description": obj.Description,
		"lossValue": obj.LossValue,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyServicePointDetailDistributionLossFactorConstraints checks if the values respects the defined constraints
func AssertEnergyServicePointDetailDistributionLossFactorConstraints(obj EnergyServicePointDetailDistributionLossFactor) error {
	return nil
}
