// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyBillingUsageTransactionV2CalculationFactors struct {

	// The value of the calculation factor
	Value float32 `json:"value"`

	// The type of the calculation factor
	Type string `json:"type"`
}

// AssertEnergyBillingUsageTransactionV2CalculationFactorsRequired checks if the required fields are not zero-ed
func AssertEnergyBillingUsageTransactionV2CalculationFactorsRequired(obj EnergyBillingUsageTransactionV2CalculationFactors) error {
	elements := map[string]interface{}{
		"value": obj.Value,
		"type": obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyBillingUsageTransactionV2CalculationFactorsConstraints checks if the values respects the defined constraints
func AssertEnergyBillingUsageTransactionV2CalculationFactorsConstraints(obj EnergyBillingUsageTransactionV2CalculationFactors) error {
	return nil
}
