// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyBillingPaymentTransaction struct {

	// The amount paid
	Amount string `json:"amount"`

	// The method of payment
	Method string `json:"method"`
}

// AssertEnergyBillingPaymentTransactionRequired checks if the required fields are not zero-ed
func AssertEnergyBillingPaymentTransactionRequired(obj EnergyBillingPaymentTransaction) error {
	elements := map[string]interface{}{
		"amount": obj.Amount,
		"method": obj.Method,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyBillingPaymentTransactionConstraints checks if the values respects the defined constraints
func AssertEnergyBillingPaymentTransactionConstraints(obj EnergyBillingPaymentTransaction) error {
	return nil
}
