// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyConcessionsResponseData struct {

	// Array may be empty if no concessions exist
	Concessions []EnergyConcession `json:"concessions"`
}

// AssertEnergyConcessionsResponseDataRequired checks if the required fields are not zero-ed
func AssertEnergyConcessionsResponseDataRequired(obj EnergyConcessionsResponseData) error {
	elements := map[string]interface{}{
		"concessions": obj.Concessions,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Concessions {
		if err := AssertEnergyConcessionRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyConcessionsResponseDataConstraints checks if the values respects the defined constraints
func AssertEnergyConcessionsResponseDataConstraints(obj EnergyConcessionsResponseData) error {
	return nil
}
