// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyBalanceListResponseDataBalances struct {

	// The ID of the account
	AccountId string `json:"accountId"`

	// The current balance of the account.  A positive value indicates that amount is owing to be paid.  A negative value indicates that the account is in credit
	Balance string `json:"balance"`
}

// AssertEnergyBalanceListResponseDataBalancesRequired checks if the required fields are not zero-ed
func AssertEnergyBalanceListResponseDataBalancesRequired(obj EnergyBalanceListResponseDataBalances) error {
	elements := map[string]interface{}{
		"accountId": obj.AccountId,
		"balance": obj.Balance,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyBalanceListResponseDataBalancesConstraints checks if the values respects the defined constraints
func AssertEnergyBalanceListResponseDataBalancesConstraints(obj EnergyBalanceListResponseDataBalances) error {
	return nil
}
