// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyDerRecordProtectionMode - Required only when the hasCentralProtectionAndControl flag is set to true.  One or more of the object fields will be provided to describe the protection modes in place
type EnergyDerRecordProtectionMode struct {

	// Maximum amount of power (kVA) that may be exported from a connection point to the grid, as monitored by a control / relay function. An absent value indicates no limit
	ExportLimitKva float32 `json:"exportLimitKva,omitempty"`

	// Protective function limit in Hz.
	UnderFrequencyProtection float32 `json:"underFrequencyProtection,omitempty"`

	// Trip delay time in seconds.
	UnderFrequencyProtectionDelay float32 `json:"underFrequencyProtectionDelay,omitempty"`

	// Protective function limit in Hz.
	OverFrequencyProtection float32 `json:"overFrequencyProtection,omitempty"`

	// Trip delay time in seconds.
	OverFrequencyProtectionDelay float32 `json:"overFrequencyProtectionDelay,omitempty"`

	// Protective function limit in V.
	UnderVoltageProtection float32 `json:"underVoltageProtection,omitempty"`

	// Trip delay time in seconds.
	UnderVoltageProtectionDelay float32 `json:"underVoltageProtectionDelay,omitempty"`

	// Protective function limit in V.
	OverVoltageProtection float32 `json:"overVoltageProtection,omitempty"`

	// Trip delay time in seconds.
	OverVoltageProtectionDelay float32 `json:"overVoltageProtectionDelay,omitempty"`

	// Sustained over voltage.
	SustainedOverVoltage float32 `json:"sustainedOverVoltage,omitempty"`

	// Sustained Over voltage protection delay in seconds.
	SustainedOverVoltageDelay float32 `json:"sustainedOverVoltageDelay,omitempty"`

	// Rate of change of frequency trip point (Hz/s).
	FrequencyRateOfChange float32 `json:"frequencyRateOfChange,omitempty"`

	// Trip angle in degrees.
	VoltageVectorShift float32 `json:"voltageVectorShift,omitempty"`

	// Description of the form of inter-trip (e.g. 'from local substation').
	InterTripScheme string `json:"interTripScheme,omitempty"`

	// Trip voltage.
	NeutralVoltageDisplacement float32 `json:"neutralVoltageDisplacement,omitempty"`
}

// AssertEnergyDerRecordProtectionModeRequired checks if the required fields are not zero-ed
func AssertEnergyDerRecordProtectionModeRequired(obj EnergyDerRecordProtectionMode) error {
	return nil
}

// AssertEnergyDerRecordProtectionModeConstraints checks if the values respects the defined constraints
func AssertEnergyDerRecordProtectionModeConstraints(obj EnergyDerRecordProtectionMode) error {
	return nil
}
