// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyAccountV2AllOf - The array of plans containing service points and associated plan details
type EnergyAccountV2AllOf struct {

	// The array of plans containing service points and associated plan details
	Plans []EnergyAccountV2AllOfPlans `json:"plans"`
}

// AssertEnergyAccountV2AllOfRequired checks if the required fields are not zero-ed
func AssertEnergyAccountV2AllOfRequired(obj EnergyAccountV2AllOf) error {
	elements := map[string]interface{}{
		"plans": obj.Plans,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Plans {
		if err := AssertEnergyAccountV2AllOfPlansRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyAccountV2AllOfConstraints checks if the values respects the defined constraints
func AssertEnergyAccountV2AllOfConstraints(obj EnergyAccountV2AllOf) error {
	return nil
}
