// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyPlanDiscountsInnerPercentOfUse - Required if methodUType is percentOfUse
type EnergyPlanDiscountsInnerPercentOfUse struct {

	// The rate of the discount applied to the usageamount
	Rate string `json:"rate"`
}

// AssertEnergyPlanDiscountsInnerPercentOfUseRequired checks if the required fields are not zero-ed
func AssertEnergyPlanDiscountsInnerPercentOfUseRequired(obj EnergyPlanDiscountsInnerPercentOfUse) error {
	elements := map[string]interface{}{
		"rate": obj.Rate,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyPlanDiscountsInnerPercentOfUseConstraints checks if the values respects the defined constraints
func AssertEnergyPlanDiscountsInnerPercentOfUseConstraints(obj EnergyPlanDiscountsInnerPercentOfUse) error {
	return nil
}
