// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type MetaPaginated struct {

	// The total number of records in the full set. See [pagination](#pagination).
	TotalRecords int32 `json:"totalRecords"`

	// The total number of pages in the full set. See [pagination](#pagination).
	TotalPages int32 `json:"totalPages"`
}

// AssertMetaPaginatedRequired checks if the required fields are not zero-ed
func AssertMetaPaginatedRequired(obj MetaPaginated) error {
	elements := map[string]interface{}{
		"totalRecords": obj.TotalRecords,
		"totalPages": obj.TotalPages,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMetaPaginatedConstraints checks if the values respects the defined constraints
func AssertMetaPaginatedConstraints(obj MetaPaginated) error {
	return nil
}
