// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyPlanDetailV3AllOf struct {

	// Charges for metering included in the plan
	MeteringCharges []EnergyPlanDetailV3AllOfMeteringCharges `json:"meteringCharges,omitempty"`

	GasContract EnergyPlanContractFullV3 `json:"gasContract,omitempty"`

	ElectricityContract EnergyPlanContractFullV3 `json:"electricityContract,omitempty"`
}

// AssertEnergyPlanDetailV3AllOfRequired checks if the required fields are not zero-ed
func AssertEnergyPlanDetailV3AllOfRequired(obj EnergyPlanDetailV3AllOf) error {
	for _, el := range obj.MeteringCharges {
		if err := AssertEnergyPlanDetailV3AllOfMeteringChargesRequired(el); err != nil {
			return err
		}
	}
	if err := AssertEnergyPlanContractFullV3Required(obj.GasContract); err != nil {
		return err
	}
	if err := AssertEnergyPlanContractFullV3Required(obj.ElectricityContract); err != nil {
		return err
	}
	return nil
}

// AssertEnergyPlanDetailV3AllOfConstraints checks if the values respects the defined constraints
func AssertEnergyPlanDetailV3AllOfConstraints(obj EnergyPlanDetailV3AllOf) error {
	return nil
}
