// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyServicePointListResponseData struct {

	ServicePoints []EnergyServicePoint `json:"servicePoints"`
}

// AssertEnergyServicePointListResponseDataRequired checks if the required fields are not zero-ed
func AssertEnergyServicePointListResponseDataRequired(obj EnergyServicePointListResponseData) error {
	elements := map[string]interface{}{
		"servicePoints": obj.ServicePoints,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.ServicePoints {
		if err := AssertEnergyServicePointRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyServicePointListResponseDataConstraints checks if the values respects the defined constraints
func AssertEnergyServicePointListResponseDataConstraints(obj EnergyServicePointListResponseData) error {
	return nil
}
