// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyPlanControlledLoadV2InnerTimeOfUseRatesInnerTimeOfUseInner struct {

	// The days that the rate applies to
	Days []string `json:"days,omitempty"`

	// The beginning of the time period per day for which the controlled load rate applies. Required if endTime provided.  Formatted according to [ISO 8601 Times](https://en.wikipedia.org/wiki/ISO_8601#Times). If the time is provided without a UTC offset, the time zone will be determined by the value of EnergyPlanContract.timeZone.
	StartTime string `json:"startTime,omitempty"`

	// The end of the time period per day for which the controlled load rate applies. Required if startTime provided.  Formatted according to [ISO 8601 Times](https://en.wikipedia.org/wiki/ISO_8601#Times). If the time is provided without a UTC offset, the time zone will be determined by the value of EnergyPlanContract.timeZone.
	EndTime string `json:"endTime,omitempty"`

	// Display text providing more information on the contrlled load, for e.g. controlled load availability if specific day/time is not known. Required if startTime and endTime absent or if additionalInfoUri provided
	AdditionalInfo string `json:"additionalInfo,omitempty"`

	// Optional link to additional information regarding the controlled load
	AdditionalInfoUri string `json:"additionalInfoUri,omitempty"`
}

// AssertEnergyPlanControlledLoadV2InnerTimeOfUseRatesInnerTimeOfUseInnerRequired checks if the required fields are not zero-ed
func AssertEnergyPlanControlledLoadV2InnerTimeOfUseRatesInnerTimeOfUseInnerRequired(obj EnergyPlanControlledLoadV2InnerTimeOfUseRatesInnerTimeOfUseInner) error {
	return nil
}

// AssertEnergyPlanControlledLoadV2InnerTimeOfUseRatesInnerTimeOfUseInnerConstraints checks if the values respects the defined constraints
func AssertEnergyPlanControlledLoadV2InnerTimeOfUseRatesInnerTimeOfUseInnerConstraints(obj EnergyPlanControlledLoadV2InnerTimeOfUseRatesInnerTimeOfUseInner) error {
	return nil
}
