// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyPlanControlledLoadV2InnerSingleRate - Object representing a single controlled load rate.  Required if rateBlockUType is singleRate
type EnergyPlanControlledLoadV2InnerSingleRate struct {

	// Display name of the controlled load rate
	DisplayName string `json:"displayName"`

	// Description of the controlled load rate
	Description string `json:"description,omitempty"`

	// The daily supply charge (exclusive of GST) for this controlled load tier
	DailySupplyCharge string `json:"dailySupplyCharge,omitempty"`

	// Array of controlled load rates in order of usage volume
	Rates []EnergyPlanControlledLoadV2InnerSingleRateRatesInner `json:"rates"`

	// Usage period for which the block rate applies. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax). Defaults to P1Y if absent
	Period string `json:"period,omitempty"`
}

// AssertEnergyPlanControlledLoadV2InnerSingleRateRequired checks if the required fields are not zero-ed
func AssertEnergyPlanControlledLoadV2InnerSingleRateRequired(obj EnergyPlanControlledLoadV2InnerSingleRate) error {
	elements := map[string]interface{}{
		"displayName": obj.DisplayName,
		"rates": obj.Rates,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Rates {
		if err := AssertEnergyPlanControlledLoadV2InnerSingleRateRatesInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyPlanControlledLoadV2InnerSingleRateConstraints checks if the values respects the defined constraints
func AssertEnergyPlanControlledLoadV2InnerSingleRateConstraints(obj EnergyPlanControlledLoadV2InnerSingleRate) error {
	return nil
}
