// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type RequestServicePointIdListData struct {

	// Array of specific servicePointIds to obtain data for
	ServicePointIds []string `json:"servicePointIds"`
}

// AssertRequestServicePointIdListDataRequired checks if the required fields are not zero-ed
func AssertRequestServicePointIdListDataRequired(obj RequestServicePointIdListData) error {
	elements := map[string]interface{}{
		"servicePointIds": obj.ServicePointIds,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRequestServicePointIdListDataConstraints checks if the values respects the defined constraints
func AssertRequestServicePointIdListDataConstraints(obj RequestServicePointIdListData) error {
	return nil
}
