// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyPaymentScheduleCardDebit - Represents a regular credit card payment schedule. Mandatory if paymentScheduleUType is set to cardDebit
type EnergyPaymentScheduleCardDebit struct {

	// The type of credit card held on file
	CardScheme string `json:"cardScheme"`

	// The frequency that payments will occur.  Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)
	PaymentFrequency string `json:"paymentFrequency"`

	// The mechanism by which the payment amount is calculated.  Explanation of values are as follows:<br/><ul><li>**STATIC** - Indicates a consistent, static amount, per payment</li><li>**BALANCE** - Indicates that the outstanding balance for the account is paid per period</li><li>**CALCULATED** - Indicates that the payment amount is variable and calculated using a pre-defined algorithm</li></ul>
	CalculationType string `json:"calculationType"`
}

// AssertEnergyPaymentScheduleCardDebitRequired checks if the required fields are not zero-ed
func AssertEnergyPaymentScheduleCardDebitRequired(obj EnergyPaymentScheduleCardDebit) error {
	elements := map[string]interface{}{
		"cardScheme": obj.CardScheme,
		"paymentFrequency": obj.PaymentFrequency,
		"calculationType": obj.CalculationType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyPaymentScheduleCardDebitConstraints checks if the values respects the defined constraints
func AssertEnergyPaymentScheduleCardDebitConstraints(obj EnergyPaymentScheduleCardDebit) error {
	return nil
}
