// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyInvoicePeriod - Object containing the start and end date for the period covered by the invoice.  Mandatory if any usage or demand based charges are included in the invoice
type EnergyInvoicePeriod struct {

	// The start date of the period covered by this invoice
	StartDate string `json:"startDate"`

	// The end date of the period covered by this invoice
	EndDate string `json:"endDate"`
}

// AssertEnergyInvoicePeriodRequired checks if the required fields are not zero-ed
func AssertEnergyInvoicePeriodRequired(obj EnergyInvoicePeriod) error {
	elements := map[string]interface{}{
		"startDate": obj.StartDate,
		"endDate": obj.EndDate,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyInvoicePeriodConstraints checks if the values respects the defined constraints
func AssertEnergyInvoicePeriodConstraints(obj EnergyInvoicePeriod) error {
	return nil
}
