// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type LinksPaginated struct {

	// Fully qualified link that generated the current response document
	Self string `json:"self"`

	// URI to the first page of this set. Mandatory if this response is not the first page
	First string `json:"first,omitempty"`

	// URI to the previous page of this set. Mandatory if this response is not the first page
	Prev string `json:"prev,omitempty"`

	// URI to the next page of this set. Mandatory if this response is not the last page
	Next string `json:"next,omitempty"`

	// URI to the last page of this set. Mandatory if this response is not the last page
	Last string `json:"last,omitempty"`
}

// AssertLinksPaginatedRequired checks if the required fields are not zero-ed
func AssertLinksPaginatedRequired(obj LinksPaginated) error {
	elements := map[string]interface{}{
		"self": obj.Self,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertLinksPaginatedConstraints checks if the values respects the defined constraints
func AssertLinksPaginatedConstraints(obj LinksPaginated) error {
	return nil
}
