// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyDerListResponseData struct {

	// Array of meter reads
	DerRecords []EnergyDerRecord `json:"derRecords"`
}

// AssertEnergyDerListResponseDataRequired checks if the required fields are not zero-ed
func AssertEnergyDerListResponseDataRequired(obj EnergyDerListResponseData) error {
	elements := map[string]interface{}{
		"derRecords": obj.DerRecords,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.DerRecords {
		if err := AssertEnergyDerRecordRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyDerListResponseDataConstraints checks if the values respects the defined constraints
func AssertEnergyDerListResponseDataConstraints(obj EnergyDerListResponseData) error {
	return nil
}
