// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type ResponseErrorListV2 struct {

	Errors []ResponseErrorListV2Errors `json:"errors"`
}

// AssertResponseErrorListV2Required checks if the required fields are not zero-ed
func AssertResponseErrorListV2Required(obj ResponseErrorListV2) error {
	elements := map[string]interface{}{
		"errors": obj.Errors,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Errors {
		if err := AssertResponseErrorListV2ErrorsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertResponseErrorListV2Constraints checks if the values respects the defined constraints
func AssertResponseErrorListV2Constraints(obj ResponseErrorListV2) error {
	return nil
}
