// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyBalanceResponseData struct {

	// The current balance of the account.  A positive value indicates that amount is owing to be paid.  A negative value indicates that the account is in credit
	Balance string `json:"balance"`
}

// AssertEnergyBalanceResponseDataRequired checks if the required fields are not zero-ed
func AssertEnergyBalanceResponseDataRequired(obj EnergyBalanceResponseData) error {
	elements := map[string]interface{}{
		"balance": obj.Balance,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEnergyBalanceResponseDataConstraints checks if the values respects the defined constraints
func AssertEnergyBalanceResponseDataConstraints(obj EnergyBalanceResponseData) error {
	return nil
}
