// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




// EnergyPlanSolarFeedInTariffV3InnerSingleTariff - Represents a constant tariff.  Mandatory if tariffUType is set to singleTariff
type EnergyPlanSolarFeedInTariffV3InnerSingleTariff struct {

	// Array of feed in rates
	Rates []EnergyPlanSolarFeedInTariffV3InnerSingleTariffRatesInner `json:"rates"`

	// Usage period for which the block rate applies. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax). Defaults to P1Y if absent
	Period string `json:"period,omitempty"`
}

// AssertEnergyPlanSolarFeedInTariffV3InnerSingleTariffRequired checks if the required fields are not zero-ed
func AssertEnergyPlanSolarFeedInTariffV3InnerSingleTariffRequired(obj EnergyPlanSolarFeedInTariffV3InnerSingleTariff) error {
	elements := map[string]interface{}{
		"rates": obj.Rates,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Rates {
		if err := AssertEnergyPlanSolarFeedInTariffV3InnerSingleTariffRatesInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEnergyPlanSolarFeedInTariffV3InnerSingleTariffConstraints checks if the values respects the defined constraints
func AssertEnergyPlanSolarFeedInTariffV3InnerSingleTariffConstraints(obj EnergyPlanSolarFeedInTariffV3InnerSingleTariff) error {
	return nil
}
