// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package energyserver




type EnergyAccountV2AllOfPlans struct {

	// Optional display name for the plan provided by the customer to help differentiate multiple plans
	Nickname string `json:"nickname,omitempty"`

	// An array of servicePointIds, representing NMIs, that this plan is linked to.  If there are no service points allocated to this plan then an empty array would be expected
	ServicePointIds []string `json:"servicePointIds"`

	PlanOverview EnergyAccountV2AllOfPlanOverview `json:"planOverview,omitempty"`
}

// AssertEnergyAccountV2AllOfPlansRequired checks if the required fields are not zero-ed
func AssertEnergyAccountV2AllOfPlansRequired(obj EnergyAccountV2AllOfPlans) error {
	elements := map[string]interface{}{
		"servicePointIds": obj.ServicePointIds,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertEnergyAccountV2AllOfPlanOverviewRequired(obj.PlanOverview); err != nil {
		return err
	}
	return nil
}

// AssertEnergyAccountV2AllOfPlansConstraints checks if the values respects the defined constraints
func AssertEnergyAccountV2AllOfPlansConstraints(obj EnergyAccountV2AllOfPlans) error {
	return nil
}
