/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package impl

import (
	"github.com/gin-gonic/gin"
)

type EnergyAPI struct{}

func (EnergyAPI) GetAccount(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) GetBalanceForAccount(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) GetBillingForAccount(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) GetConcessions(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) GetDERForServicePoint(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) GetInvoicesForAccount(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) GetPaymentSchedule(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) GetPlan(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) GetServicePoint(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) GetUsageForServicePoint(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListAccounts(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListBalancesBulk(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListBalancesForAccounts(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListBillingBulk(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListBillingForAccounts(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListDERBulk(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListDERForServicePoints(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListInvoicesBulk(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListInvoicesForAccounts(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListPlans(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListServicePoints(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListUsageBulk(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (EnergyAPI) ListUsageForServicePoints(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}
