/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package impl

import (
	"github.com/gin-gonic/gin"
)

type GenericTariffsAPI struct{}

func (GenericTariffsAPI) GetPlan(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}

func (GenericTariffsAPI) ListPlans(c *gin.Context) {
	//TODO implement me
	panic("implement me")
}
