/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/nanikjava/cdsenergy/v1/impl"
	"log"

	// WARNING!
	// Pass --git-repo-id and --git-user-id properties when generating the code
	//
	sw "github.com/nanikjava/cdsenergy/v1/pkg/gen"
)

func main() {
	routes := sw.ApiHandleFunctions{}
	routes.BillingAPI = &impl.BillingService{}
	routes.EnergyAPI = &impl.EnergyAPI{}
	routes.EnergyAccountsAPI = &impl.EnergyAccountsAPI{}
	routes.ElectricityUsageAPI = &impl.ElectricityUsageAPI{}
	routes.DistributedEnergyResourcesAPI = &impl.DistributedEnergyResourcesService{}
	routes.NMIStandingDataAPI = &impl.NMIStandingDataAPI{}
	routes.GenericTariffsAPI = &impl.GenericTariffsAPI{}

	log.Printf("Server started")

	router := sw.NewRouter(routes)

	log.Fatal(router.Run(":8888"))
}
