// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CDR Energy API
 *
 * Consumer Data Right end points and payloads for the Energy sector
 *
 * API version: 1.30.0
 */

package main

import (
	energyserver "github.com/nanikjava/cdsenergy/v1/pkg/pkg"
	"log"
	"net/http"

)

func main() {
	log.Printf("Server started")

	DefaultAPIService := energyserver.NewDefaultAPIService()
	DefaultAPIController := energyserver.NewDefaultAPIController(DefaultAPIService)

	router := energyserver.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":8888", router))
}
